version: "3.8"
services:
    # NGINX Server
    web-server:
        image: nginx:latest
        container_name: markdown-note-server
        restart: always
        hostname: markdown-note-service
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    # Express Typescript API
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: markdown-note-back-end
        restart: always
        environment:
            PORT: ${API_PORT}
        hostname: markdown-note-api
        volumes:
            - ./api:/app
            - /app/node_modules
        networks:
            - app-network

    # Vite React Typescript
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: markdown-note-front-end
        restart: always
        environment:
            PORT: ${CLIENT_PORT}
        hostname: markdown-note-client
        volumes:
            - ./client:/app
            - /app/node_modules
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
